This error was resolved after i created a new env and installed jupyter in it. <br>
Steps to create <a href="https://github.com/akanksha21singh/AnacondaSolutions/blob/main/creating%20new%20env%20in%20anaconda">new environment
